### ISSUE TITLE
What is the advantage of CRakNetPlusPlus compared to the official RakNet?

### ISSUE THREAD

**Issue by shuizhihun** [CRakNetPlusPlus/CRakNetPlusPlus#1]

**Comment by MarfGamer** [comment]
CRakNetPlusPlus is simply a port of JRakNet to C++, with mostly the same style of it's Java version equivalent. All the other ports (PyRaknet, GoRakNet, NodeRakNet, etc.) are also ports to provide a way for people who code in those languages to have the ability to use the RakNet protocol.

For me personally, even though I might not code in those languages much, it is also great practice for me as I have to do a lot of coding in said language. I have already learned more about C++ than in the past 2 years since I've had to do a lot of thinking to get certain things done (Just getting the ping and pong to work took 3 weeks!)

**Comment by dschwartz783** [comment]
The RakNet API is the simplest API I've ever seen to use. Literally, everything you need is in RakPeer. RakNet is well documented in its header files, making it quite easy to use.

**Comment by MarfGamer** [comment]
@dschwartz783 Interesting, could you send me where you found the documentation that you were talking about?

**Comment by dschwartz783** [comment]
@MarfGamer The main header file: https://github.com/facebookarchive/RakNet/blob/master/Source/RakPeer.h
Each function is well documented.
